### ISSUE TITLE
Inject dependencies on child controller

### ISSUE THREAD

**Issue by figalex** [wuxiaoying/classy-extends#2]
I'm trying to inject a service that is only required on this child controller but it gets "undefined". Is it possible to inject dependencies on child controllers?

**Comment by wuxiaoying** [comment]
It should be possible to inject dependencies on child controllers now. The code was originally written pre classy 1.0, so there was some stuff that broke this functionality. I'll have to look again at the classy 1.0 changes carefully later too :).

**Comment by wuxiaoying** [comment]
Sorry, there is still an issue with localInject and dependency ordering here
